# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_change_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
