# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-28 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0004_auto_20171216_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.CategoryType'),
        ),
        migrations.AlterField(
            model_name='questionvotes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter.Question'),
        ),
        migrations.AlterField(
            model_name='questionvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
